[package]
name = "audio_mixer"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[features]
ogg = ["lewton"]
wav = ["hound"]

[dependencies]
atomic_float = "*"
cpal = "*"
lewton = { version = "*", optional = true }
hound = { version = "*", optional = true }
